#!/sbin/sh
# AnyKernel2 Backend
# osm0sis @ xda-developers

OUTFD=/proc/self/fd/$2;
ZIP="$3";
DIR=`dirname "$ZIP"`;

ui_print() {
  until [ ! "$1" ]; do
    echo -e "ui_print $1\nui_print" > $OUTFD;
    shift;
  done;
}
show_progress() { echo "progress $1 $2" > $OUTFD; }
set_perm_recursive() {
  dirs=$(echo $* | awk '{ print substr($0, index($0,$5)) }');
  for i in $dirs; do
    chown -R $1.$2 $i; chown -R $1:$2 $i;
    find "$i" -type d -exec chmod $3 {} +;
    find "$i" -type f -exec chmod $4 {} +;
  done;
}
file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
getprop() { test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1; }
abort() { ui_print "$*"; exit 1; }

mkdir -p /tmp/nethunterkernel;
cd /tmp/nethunterkernel;
unzip -o "$ZIP";

ui_print "**********************";
ui_print "$(file_getprop /tmp/nethunterkernel/anykernel.sh kernel.string)";
ui_print " AnyKernel2 by osm0sis @ xda-developers";
ui_print "**********************";
/tmp/busybox mount /system;

if [ "$(file_getprop /tmp/nethunterkernel/anykernel.sh do.devicecheck)" == 1 ]; then
  ui_print "- Checking device...";
  for i in 1 2 3 4 5; do
    testname="$(file_getprop /tmp/nethunterkernel/anykernel.sh device.name$i)";
    if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
      match=1;
    fi;
  done;
  if [ "$match" != 1 ]; then
    umount /system;
    abort "- Unsupported device. Aborting...";
  fi;
fi;

if [ "$(file_getprop /tmp/nethunterkernel/anykernel.sh do.initd)" == 1 ]; then
  ui_print "- Creating init.d...";
  mkdir /system/etc/init.d;
  set_perm_recursive 0 0 0755 0755 /system/etc/init.d;
fi;

ui_print "- Starting kernel installation...";
/sbin/sh /tmp/nethunterkernel/anykernel.sh;
if [ "$(cat /tmp/nethunterkernel/exitcode)" == 1 ]; then 
  umount /system;
  abort;
fi;

if [ "$(file_getprop /tmp/nethunterkernel/anykernel.sh do.modules)" == 1 ]; then
  ui_print "- Pushing modules...";
  cp -f /tmp/nethunterkernel/modules/* /system/lib/modules/;
  set_perm_recursive 0 0 0755 0644 /system/lib/modules;
fi;

# [Nethunter] Fix for Cyanogenmod jackpal terminal launching
# We can pass a no-op ":"  in case resize is in a function. (CM12+ adds it inside function)
/tmp/busybox sed -i 's/resize/:/g' /system/etc/mkshrc

ui_print "- Kernel installation completed";